"""Add sections and course code

Revision ID: 18da443d6be7
Revises: f73c52507ca3
Create Date: 2026-04-20 13:16:22.890923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18da443d6be7'
down_revision: Union[str, Sequence[str], None] = 'f73c52507ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_code', sa.String(), server_default='', nullable=False))
    op.add_column('courses', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'section_id')
    op.drop_column('courses', 'course_code')
    # ### end Alembic commands ###
