"""add answers column to quiz_attempt

Revision ID: 4f0d408057dd
Revises: 18da443d6be7
Create Date: 2026-04-20 17:30:09.916012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0d408057dd'
down_revision: Union[str, Sequence[str], None] = '18da443d6be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('answers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'answers')
    # ### end Alembic commands ###
