"""add_rubric_scoring_columns

Revision ID: ed5529d0b5e8
Revises: 4f0d408057dd
Create Date: 2026-05-17 21:38:32.951190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5529d0b5e8'
down_revision: Union[str, Sequence[str], None] = '4f0d408057dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('rubric_score', sa.Float(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('rubric_feedback', sa.JSON(), nullable=True))
    op.add_column('assignments', sa.Column('rubric', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'rubric')
    op.drop_column('assignment_submissions', 'rubric_feedback')
    op.drop_column('assignment_submissions', 'rubric_score')
    # ### end Alembic commands ###
